-- drop.sql
DROP FUNCTION IF EXISTS update_timestamp() CASCADE;

DROP TABLE IF EXISTS journey_tags CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS photos CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS journey_participants CASCADE;
DROP TABLE IF EXISTS journeys CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;